apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: apps
  labels: { app: http-echo, variant: bar }
spec:
  replicas: 6
  selector: { matchLabels: { app: http-echo, variant: bar } }
  template:
    metadata:
      labels: { app: http-echo, variant: bar }
    spec:
      # shareProcessNamespace: true
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0.0
          args: ["-text=bar", "-listen=:5678"]
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet: { path: "/", port: 5678 }
            initialDelaySeconds: 1
            periodSeconds: 2
          resources:
            requests: { cpu: "10m", memory: "16Mi" }
            limits:   { cpu: "200m", memory: "64Mi" }
        # - name: debug
        #   image: radial/busyboxplus:curl
        #   command: ["sh", "-c", "sleep infinity"]
        #   stdin: true
        #   tty: true
        #   resources:
        #     requests: { cpu: "5m", memory: "8Mi" }
        #     limits:   { cpu: "50m", memory: "64Mi" }
