name: ci-load-test

on:
  pull_request:
    branches: [ main ]
    paths:
      - "kind-goodnotes-k8s-demo/apps/**"
      - ”scripts/**“

jobs:
  k8s-load-test:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.32.0

      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy apps for deployments
        run: |
          kubectl apply -k kind-goodnotes-k8s-demo/apps/foo
          kubectl apply -k kind-goodnotes-k8s-demo/apps/bar
          kubectl rollout status deployment/foo -n apps --timeout=120s
          kubectl rollout status deployment/bar -n apps --timeout=120s
          sleep 10

      - name: Verify ingress routing
        run: |
          curl -fsSL -H "Host: foo.localhost" http://127.0.0.1:8080
          curl -fsSL -H "Host: bar.localhost" http://127.0.0.1:8080

      - name: Install load test dependencies
        run: |
          python3.12 -m pip install --upgrade pip aiohttp

      - name: Run load test
        run: |
          python3.12 scripts/load-test.py 10000 50 | tee loadtest.json

      - name: Post result to PR comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('loadtest.json', 'utf8');
            const body = [
              '### Load Test Result',
              '',
              '```json',
              results,
              '```'
            ].join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
